pool:
  vmImage: windows-latest

# Disables automatic triggers
trigger: none

resources:
  repositories:
    - repository: scraper
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-scraper

variables:
  - template: variables/main.yml
  - template: variables/scraper.yml

stages:
- stage: Stage
  jobs:
    - job: Stage
      displayName: Stage RP model exports
      dependsOn: []
      steps:
        - template: templates/setup-scraper.yml

        - script: py main_rp_model_stage.py
          displayName: 'Stage RP model data'
          env:
            PKS_MONGODB_URI: $(MONGODB_URI)
            # This is needed, or it could have a weird error of `No module named`
            # https://stackoverflow.com/a/32368673/11571888
            PYTHONPATH: .

        - task: CopyFiles@2
          displayName: 'Copy Artifact Files'
          inputs:
            SourceFolder: '.'
            # Copy everything for artifact creation, except the assets because it's too big and not being used
            Contents: |
              **/*
              !data/assets/**
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: ArchiveFiles@2
          displayName: 'Archive Build Artifacts'

          inputs:
            rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Build Artifacts'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).zip'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'
