pool:
  vmImage: windows-latest

# Disables automatic triggers
trigger: none

schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Run
  branches:
    include:
    - main
  always: true

resources:
  repositories:
    - repository: scraper
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-scraper

variables:
  - template: variables/scraper.yml

stages:
- stage: Deploy
  jobs:
  - job: Deploy

    steps:
    - template: templates/setup-scraper.yml

    - script: |
        git config --global user.email "raenonx0710@gmail.com"
        git config --global user.name "RaenonX (RP Model Automation)"
      displayName: 'Setup Git Credentials'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script: py main_rp_model_refresh.py
      displayName: 'Refresh RP Model Pickles'
      env:
        # This is needed, or it could have a weird error of `No module named`
        # https://stackoverflow.com/a/32368673/11571888
        PYTHONPATH: .

    - script: |
        git checkout -b main
        git add -A
        git commit -m "[AUTO] RP Model Pickle Refresh"
        git push --set-upstream origin main -f
      displayName: Commit & Push
      workingDirectory: $(System.DefaultWorkingDirectory)
